### PR TITLE
Disable ActiveTcl 8.6.6

### LINKED ISSUE #242: ActiveTcl 8.6.6.8606 is not available
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/a9g3n8yiy7gatau4#L61

### LINKED ISSUE #244: No release for 5 days, anything wrong ?
Expecting the latest command line pum feature in GVim.

### PR DESCRIPTION
**Pull request by k-takata**
ActiveTcl 8.6.6 is not available anymore. Disable it for now.

Close #242
Close #244

### CODE REVIEW

**Comment by skywind3000** [comment]
this makes sense, someone who really care about activetcl can still compile gvim by themselves.

**Comment by chrisbra** [comment]
let's merge it for now

**Comment by skywind3000** [comment]
Thanks, @chrisbra , may I ask for a new GVim release now ? can't wait to try the new command line pum.

**Comment by chrisbra** [comment]
If all goes well, there should be a new release in about 4 hours.

**Pull request merged**
