### PR TITLE
Reduce time for creating Ruby's config.h

### PR DESCRIPTION
**Pull request by k-takata**
No need to extract whole Ruby source to create config.h.
Extract only required files.

Also add some error checking and reduce some log messages.

### CODE REVIEW

**Comment by chrisbra** [comment]
I think looks good, although I scratched my head around the 7z syntax.  I suppose this worked in your local fork?

**Comment by k-takata** [comment]
Yes, this is tested:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/job/t5bm8hwpkvm5sopu#L69
(It stopped at another reason, though.)

We only need the following files for creating config.h:

```
./bin/*
./common.mk
./enc/Makefile.in
./include/ruby/version.h
./version.h
./win32/* (except *.c, *.h and README.*)
```

**Comment by chrisbra** [comment]
okay good. How about adding a part of your commit message as comment "Note that we need to use `^^` to escape `!` because we enable delayed expansion."

**Comment by k-takata** [comment]
Done.

**Comment by chrisbra** [comment]
thanks!

**Pull request merged**
