### PR TITLE
Show build log of GvimExt and set CPU explicitly

### PR DESCRIPTION
**Pull request by k-takata**
Show the build log of GvimExt for debugging.

(I also need to update the URL of Racket. The old URL doesn't respond now.)

### CODE REVIEW

**Comment by k-takata** [comment]
Setting CPU explicitly seems to fix the problem.

**Comment by chrisbra** [comment]
thanks

**Comment by chrisbra** [comment]
Hm, the racket URLs look strange. Doesn't it work to use `download.racket-lang.org` instead of `mirror`. According to the official racket site, we should just use:

    32bit: https://download.racket-lang.org/releases/6.10.1/installers/racket-minimal-6.10.1-i386-
win32.exe
    64bit: https://download.racket-lang.org/releases/6.10.1/installers/racket-minimal-6.10.1-x86_64-win32.exe

**Comment by k-takata** [comment]
Oh, I didn't know that.

**Pull request merged**
