### PR TITLE
Update gettext-iconv-windows to v0.22.5a-v1.17

### PR DESCRIPTION
**Pull request by k-takata**
https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.22.5a-v1.17

### CODE REVIEW

**Comment by k-takata** [comment]
Hmm, 32-bit version of libintl-8.dll requires libgcc_s_sjlj-1.dll again.

**Comment by mlocati** [comment]
> Hmm, 32-bit version of libintl-8.dll requires libgcc_s_sjlj-1.dll again.

Let's see if https://github.com/mlocati/gettext-iconv-windows/pull/24 works

**Comment by k-takata** [comment]
I checked the artifacts in https://github.com/mlocati/gettext-iconv-windows/actions/runs/11165407674, but libintl-8.dll still depends on libgcc_s_sjlj-1.dll.

**Comment by k-takata** [comment]
I consider including libgcc_s_sjlj-1.dll again.
To make this work, we should also update gvim.nsi. (Need to revert the part of https://github.com/vim/vim/commit/49f1e1979f9c3a4d7b28f0961bca0e41227a0557.)

**Comment by k-takata** [comment]
> To make this work, we should also update gvim.nsi.

https://github.com/vim/vim/pull/15819

**Comment by k-takata** [comment]
libgcc_s_sjlj-1.dll is included in the packages now:
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/builds/50750908/job/jjoeu834bp69p918/artifacts

**Pull request merged**
