### PR TITLE
 Switch to Strawberry Perl from ActivePerl

### PR DESCRIPTION
**Pull request by k-takata**
See #60.
Also update to Perl 5.28.

I confirmed that this worked fine on my AppVeyor account:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/job/r1uw4ssemawr9y85

If we switch to Strawberry Perl, we should also update `if_perl.txt`:
https://github.com/vim/vim/blob/fda95e75721fb221495c69e493ec2761b5d85123/runtime/doc/if_perl.txt#L48
https://github.com/vim/vim/blob/fda95e75721fb221495c69e493ec2761b5d85123/runtime/doc/if_perl.txt#L284-L285

I will wait @brammool's opinion before merge this.

### CODE REVIEW

**Comment by k-takata** [comment]
(off topic)
I found that [the line 47 in if_perl.txt](https://github.com/vim/vim/blob/fda95e75721fb221495c69e493ec2761b5d85123/runtime/doc/if_perl.txt#L47) links to http://www.perl.com,
but [the line 284](https://github.com/vim/vim/blob/fda95e75721fb221495c69e493ec2761b5d85123/runtime/doc/if_perl.txt#L284) links to http://www.perl.org.
I think perl.com is a mistake of perl.org.
Moreover, I think the lines 47-48 can be removed because they are duplicate of the lines 284-285.

**Comment by chrisbra** [comment]
okay good

**Comment by brammool** [comment]
I have no preference for a specific Perl implementation.   I'll leav it up to the experts.

**Comment by chrisbra** [comment]
if nothing speaks against it, I all for merging (and will go ahead and merge within the next 7 days).

**Comment by chrisbra** [comment]
I merged it. let's see if people notice and complain

**Pull request merged**
