### PR TITLE
Revise changelog

### PR DESCRIPTION
**Pull request by k-takata**
* Add link to each commit instead of each tag.
  (I don't think that link to each tag is so useful.)
  This also adds a link to runtime files update.
* Simplify the sed expressions. Bram has changed the style of commit log
  a few years ago. No need to drop 'Problem:' or limit to 100 characters anymore.
* Use separate commands for creating changelog for markdown and plain text.

### CODE REVIEW

**Comment by chrisbra** [comment]
> This also adds a link to runtime files update.

Why did this not work?

**Comment by chrisbra** [comment]
ah nevermind, I think the old script was still executed

**Comment by k-takata** [comment]
I assume you are running `update-repo.sh` once per day on your server, then it has one cycle delay for the updated script being used. How about executing `git pull` before executing `update-repo.sh`?

**Comment by k-takata** [comment]
Another idea is executing `update-repo.sh` on AppVeyor. I do this in [ctags-win32](https://github.com/universal-ctags/ctags-win32), but this needs some work and settings.

**Comment by chrisbra** [comment]
> How about executing git pull before executing update-repo.sh

good idea.

> Another idea is executing update-repo.sh on AppVeyor

I believe this is what the vim-appimage repo does. But I don't think this is necessary currently.

**Pull request merged**
