### PR TITLE
The removal of the UPX definition is commented out

### PR DESCRIPTION
**Pull request by RestorerZ**
The removal of the UPX definition is commented out

### CODE REVIEW

**Comment by RestorerZ** [comment]
@chrisbra , you have in the parameters "nmake.exe " the variable "MBYTE" is specified. Tell me, please, what kind of variable is this? I just didn't find it in "Make_mvc.mak", nor in "feature.h", nor in the documentation.

**Comment by k-takata** [comment]
`MBYTE` is an old option which has been removed and always enabled now.

**Comment by RestorerZ** [comment]
Thank you very much! It's clear now.

**Comment by chrisbra** [comment]
thanks! Let me merge it.

**Pull request merged**
