### PR TITLE
Update for 8.0.0961

### PR DESCRIPTION
**Pull request by k-takata**
Remove the temporary patch, and adjust the path of winpty files.

### CODE REVIEW

**Comment by chrisbra** [comment]
sorry, I just removed the patch. Can you please rebase on top and just add the change to appveyor.bat?

**Comment by k-takata** [comment]
I think it can be merged cleanly even without rebasing.

**Comment by chrisbra** [comment]
thanks.

**Comment by chrisbra** [comment]
Hm, i was perhaps a bit fast with merging that. Do we need winpty in both directory, runtime and the top level root?

**Comment by k-takata** [comment]
8.0.0961 is different from my temporary patch. It uses `${VIMTOOLS}` instead of `${VIMRT}`.
`${VIMRT}` is pointing `..\runtime` and `${VIMTOOLS}` is pointing `..\..`, so the modification to the batch file is needed.

**Comment by k-takata** [comment]
Copying the winpty files to `..\runtime` is needed for creating zip packages. So both are needed.

**Pull request merged**
