### PR TITLE
update raco to 8.7 bc

### PR DESCRIPTION
**Pull request by zewpo**
Worth trying, the installer on VS 2022 seems to build with it - along with a couple mods to tbe bat file.  Lets see how it goes.

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks,
I have just merged the update of Racket (plus updated the version number in some of the other files). 

I don't know if we need the github actions thing, so I left it out for now.

**Review by zewpo — COMMENTED** [review]
It seems to work, I downloaded the artifacts from this appveyor and installed it on my pc.  I only tried the following;

:mz (apply + '(1 2))

and it gave 3

My local drracket install was just done through the standard installer. 
racket-8.7-x86_64-win32-bc.exe

from here;

https://download.racket-lang.org/releases/8.7/installers/racket-8.7-x86_64-win32-bc.exe

For vims interface to scheme to work on my pc, I also had to manually configure these environment variables;
set PLTCOLLECTS="C:\Program Files\Racket\collects"
set PLTCONFIGDIR="C:\Program Files\Racket\collects\etc"

Then vim could find the collections.

I dont know what else to test, as I'm not a regular user of lispy things.

Oh, I did manually run this; 
` raco pkg install -i --auto racket`

Not sure if it was really needed though, because I ran it while trying to find why it couldn't find the collections.   racket/base was something it complained about.   So, it may or may not have been needed.   


Edit:  lol - as this has a typo:   
`set PLTCONFIGDIR="C:\Program Files\Racket\collects\etc"`
Then it probably was not necessary for my initial test anyway...

**Comment by zewpo** [comment]
@chrisbra 

no worries about the gha thing.   yeah, its still unstable - and just something I'm playing with.

Actually, although I asked if that's what you meant, aftward I realised it wasn't what you were requesting - obviously based on the context of the discussion.  ;p

**Comment by zewpo** [comment]
closing merged in https://github.com/vim/vim-win32-installer/commit/5258c123b13a6fe5ca468424356fed1523b7638a

**Pull request closed without merging**
